name: Build and deploy the Sestrel app with expo

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Install, test and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Using node version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Getting yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      
      - name: Caching dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Installing dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Using expo github action (v5)
        uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

      #  - name: Build expo app and create url artifact
      #    run: expo build:android -t apk
        
      - name: Displaying and saving the expo apk url for the next download step
        id: expo-apk-url
        run: echo "::set-output name=apk-url::$(expo url:apk)"

      - name: Downloading the built apk from expo.io
        # run: wget -O sestrel-android-app.apk $(expo url:apk)
        # run: wget -O sestrel-android-app.apk ${{ steps.expo-apk-url.outputs.apk-url }}
        run: curl ${{ steps.expo-apk-url.outputs.apk-url }} --output sestrel-android-app.apk
        working-directory: /downloads

      - name: Uploadinging the as an artifact to use it in the "deploy" job
        uses: actions/upload-artifact@v2
        with:
          name: sestrel-android-app
          path: /downloads/sestrel-android-app.apk

  deploy:
    needs: build
    name: Download and deploy the setrel app
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the sestrel app from "build" job
        uses: actions/download-artifact@v2
        with:
          name: sestrel-android-app
          path: /downloads/sestrel-android-app.apk
        
      - name: Displaying structure of downloaded file
        run: ls -R
        working-directory: /downloads

      - name: transfering the sestrel apk to sestrel server with Scp (Secure Copy) 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_GITHUB_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_GITHUB_USERNAME }}
          password: ${{ secrets.DIGITAL_OCEAN_GITHUB_PASSWORD }}
          # port: ${{ secrets.SESTREL_PORT }}
          source: /downloads
          target: /var/www/public

