name: Build and deploy the Sestrel app with expo

on:
  # pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Install, test and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
      - uses: actions/checkout@v2
      - name: Using node version 12.x
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Installing dependencies
      - run: yarn install
      - name: Running tests
      - run: yarn test
      - name: Build expo app and create url artifact
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      # - run: expo build:android -t apk
      # - run: expo url:apk > apk-url.txt
