name: Build and deploy the Sestrel app with expo

on:
  push:
    branches:
      - test
jobs:
  build:
    name: Install, test and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display githug.ref value
        run: echo ${{ github.ref }}

      - name: Find and Replace
        id: find-and-replace
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: '\*+(?=\/)'
          string: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40*************/stlp-ui-b029f00fceaf41e9918138057804feb8-signed.apk
          # replace-with: ${{ secrets.EXPO_CLI_USERNAME }}
          replace-with: atcheri

      - name: branch
        run: echo "${{ steps.find-and-replace.outputs.replaced }}"
