name: Build and deploy the Sestrel app with expo

on:
  push:
    branches:
      - test
jobs:
  build:
    name: Install, test and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display githug.ref value
        run: echo ${{ github.ref }}

      - name: Find and Replace
        id: find-and-replace
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: '\*+(?=\/)'
          string: ${{ github.ref }}
          replace-with: ${{ secrets.EXPO_CLI_USERNAME }}

      - name: branch
        run: echo "${{ steps.find-and-replace.branch.outputs.replaced }}"
